ekf_node:
  ros__parameters:
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom  # Why not 'map' ? 
    publish_tf: true
    two_d_mode: true
    frequency: 50.0
    
    odom0: camera_pose
    odom0_config: [true,  true,  false, # false, false, false, # displacement
                   false, false, true,  # false, false, false, # angular rotation
                   true,  true,  false, 
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_queue_size: 10
    odom0_relative: true

    imu1: rs_cam/imu
    imu1_config: [false, false, false,   # displacement 
                  false, false, true,    # angular rotation 
                  false, false, false,   # velocity 
                  false, false, true,    # angular velocity 
                  true,  false, false]   # acceleration 
    imu1_differential: false  
    imu1_queue_size: 10
    imu1_relative: true
